GRADLE = ./gradlew


chess:
	$(GRADLE) install runChess -q

tictactoe:
	$(GRADLE) install runTicTacToe -q

graph:
	$(GRADLE) install runGraph -q

maze:
	$(GRADLE) install runMazeDepth -q

install:
	$(GRADLE) install -x test -q