/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vertexacademy.neuralnetwork;

import java.util.Arrays;
import org.junit.Test;
import static org.junit.Assert.*;

public class NeuronTest {
    
    /*
    *   La methode testNeuronFireOne prouve que le neurone apres
    *   activation retourne 1.
    */
    @Test 
    public void testNeuronFireOne() {
        
        double[] weights = {1, 2};
        double[] inputs  = {5, 2};

        Neuron n = new Neuron(2);
        n.setWeights(weights);
        n.setBias(-2);
        
        assertEquals("neuron should fire one", n.feed(inputs), 1);
    }

    /*
    *   La methode testNeuronFireZero prouve que le neurone apres
    *   activation retourne 0.
    */
    @Test 
    public void testNeuronFireZero() {
        
        Neuron n = new Neuron(2);
        n.setWeights(new double[]{1, 2});
        n.setBias(-2);

        assertEquals("neuron should fire zero", 
                        n.feed(new double[]{-2, 2}), 0);
    }

    /*
    *   La methode testAND prouve le bon fonctionnement d'un neurone
    *   sur la realisation d'une table de verite pour la porte logique AND. 
    */
    @Test
    public void testAND() {

        // Deux entrees comme la porte logique AND
        Neuron n = new Neuron(2);

        n.setWeights(new double[]{1, 1});
        n.setBias(-1.5);

        assertEquals(" 0 AND 0 should return 0", n.feed(new double[]{0,0}), 0);
        assertEquals(" 0 AND 1 should return 0", n.feed(new double[]{0,1}), 0);
        assertEquals(" 1 AND 0 should return 0", n.feed(new double[]{1,0}), 0);
        assertEquals(" 1 AND 1 should return 1", n.feed(new double[]{1,1}), 1);
    }

    /*
    *   La methode testOR prouve le bon fonctionnement d'un neurone
    *   sur la realisation d'une table de verite pour la porte logique OR
    */
    @Test
    public void testOR() {
        Neuron n = new Neuron(2);

        n.setWeights(new double[]{1, 1});
        n.setBias(-0.5);

        assertEquals(" 0 OR 0 should return 0", n.feed(new double[]{0, 0}), 0);
        assertEquals(" 0 OR 1 should return 1", n.feed(new double[]{0, 1}), 1);
        assertEquals(" 1 OR 0 should return 1", n.feed(new double[]{1, 0}), 1);
        assertEquals(" 1 OR 1 should return 1", n.feed(new double[]{1, 1}), 1);
    }

    /*
    *   La methode testNOR est une negation de la porte logique OR tout simplement.
    *
    */
    @Test
    public void testNOR() {
        Neuron n = new Neuron(2);

        n.setWeights(new double[]{-1, -1});
        n.setBias(0.5);

        assertEquals(" 0 NOR 0 should return 1", n.feed(new double[]{0, 0}), 1);
        assertEquals(" 0 NOR 1 should return 0", n.feed(new double[]{0, 1}), 0);
        assertEquals(" 1 NOR 0 should return 0", n.feed(new double[]{1, 0}), 0);
        assertEquals(" 1 NOR 1 should return 0", n.feed(new double[]{1, 1}), 0);
    }

    /*
    *   La methode NOT permet de tester le neuron avec un tensor de dim 1
    *   applique a son entree.
    *
    */
    @Test
    public void testNOT() {
        Neuron n = new Neuron(1);

        n.setWeights(new double[]{-1});
        n.setBias(0.5);

        assertEquals(" NOT 0 should return 1", n.feed(new double[]{0}), 1);
        assertEquals(" NOT 1 should return 0", n.feed(new double[]{1}), 0);
    }

    /*
    *   La methode testWrongFeeding permet de configurer qu'une erreur lors
    *   du passage de parametre a la methode feed doit lever une exception.
    */
    @Test
    public void testWrongFeeding() {

        Neuron n = new Neuron(1);

        n.setWeights(new double[]{-1});
        n.setBias(0.5);

        assertThrows(IllegalArgumentException.class, () -> {
            n.feed(new double[]{1, 1});
        });
    }
}
