/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vertexacademy.neuralnetwork;

import java.util.Arrays;
import org.junit.Test;
import static org.junit.Assert.*;

public class NeuronTest {
    @Test public void neuronHasAGreeting() {
        Neuron classUnderTest = new Neuron(3);
        assertNotNull("neuron should have a greeting", classUnderTest.getGreeting());
    }
}
